Rox/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'landing#index'
  
  get'/home' => 'home#index'


  resources :users

  resources :trips, only: [:index, :new, :create, :show, :destroy] do

    resources :trip_registrations, only: [:create]
  end

  resources :trip_registrations, only: [:update, :destroy]

  get 'my_trips' => 'users#user_trip_search'

  # get '/api/trips' => 'trips#serve'

  namespace :api, defaults: { format: :json } do
    resources :trips, only: [:index]
  end

end

Rox/app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :departure, presence: true

  belongs_to :driver, class_name: "User", foreign_key: :user_id
  has_many :trip_registrations, dependent: :destroy
  has_many :passengers, class_name: "User", through: :trip_registrations

  default_scope { order('departure ASC') }

  def self.trip_find(date = Date.current)
    order("title ASC").where("created_at > ?", date).limit(10)
  end

  def regs
    p = { accepted:[] }
    p[:total] = trip_registrations.length
    # p[:all] = trip_registrations.to_ary
    trip_registrations.to_ary.each do |r|
      puts "p[r.status]=#{p[r.status]}"
      p[r.status.to_sym] ||= []
      p[r.status.to_sym] << r
    end
    return p
  end

  def self.later_this_month(date = Date.current)
    Trip.all.where("departure <= ?", date.end_of_month).limit(5)
  end

  def self.most_popular
    Trip.joins(:trip_registrations).group("trips.id").order("COUNT (*) DESC ").limit(5).count
  end

end

Rox/app/models/trip_registration.rb
class TripRegistration < ActiveRecord::Base
  belongs_to :trip
  belongs_to :passenger, class_name: "User", foreign_key: :user_id

  # def self.pending_find
  #   @trip_registrations = TripRegistrations.where()
    
  # end
end

Rox/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :trips, dependent: :destroy
  has_many :trip_registrations, dependent: :destroy
  has_many :lifts, through: :trip_registrations, source: :trip
  

  def on_trip?(trip)
    self.trip_registrations.where(trip_id: trip.id).size > 0
  end

  def trip_status(trip)
    self.trip_registrations.find_by(trip_id: trip.id).status
    
  end

  def later_this_month(date = Date.current)
    self.trips.where("departure >= ?", date.end_of_month).limit(5)
  end

  def upcoming(date = Date.current)
    self.trips.where("departure >= ?", date).limit(2)
  end

  def soon(date = Date.current)
    self.lifts.where("departure >= ?", date).limit(2)
  end

end

Rox/app/controllers/api/trips_controller.rb
class Api::TripsController < ApplicationController

  def index
    @trips = Trip.where.not(latitude: [nil], departure: [nil]) 
    render status: 200, json: @trips
  end
end

Rox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :resource_name, :resource, :devise_mapping

  private

  
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name 
    end

    def authorize_user
      unless user_signed_in?
        flash[:danger] = "Please log in or register to access this page"
        redirect_to root_path
      end
    end

end

Rox/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

Rox/app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    if current_user.present?
      redirect_to home_path
    end
    @new_user_session = User.new
  end
end

Rox/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

Rox/app/controllers/trip_registrations_controller.rb
class TripRegistrationsController < ApplicationController

  def create
    @trip_registration = current_user.trip_registrations.new(status: "pending", trip_id: params[:trip_id])
    if @trip_registration.save
        flash[:success] = "Great! Your request has been sent."
        redirect_to trip_path(id: params[:trip_id])
    else
      flash[:danger] = "we were unable to register your request."
      redirect_to root_path
    end
  end

  def update
    @trip_registration = TripRegistration.find(params[:id])

    if @trip_registration.update(status: params[:status])
      flash[:success] = "Status updated successfully!"
      render json: @trip_registration
    else
      flash[:danger] = "We couldn't update the status of this request unfortunately. Please try again."
      redirect_to trips_path
    end
  end

end

Rox/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authorize_user

  def index
    @trips = Trip.where("departure >= :today", today: Time.now)
    @next_trips = Trip.later_this_month 
  end

  def new
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.valid?
      @trip.save
      flash[:success] = "You have successfully created a trip, Better get training for your next project!"
      redirect_to trip_path(@trip)
    else
      flash[:danger] = "All fields need to be completed to create a trip."
      render :new
    end
  end

  def show
    unless current_user
      flash[:warning] = "Please sign up or log in to view this page."
      redirect_to new_user_registration_path
    end
    @trip = Trip.find(params[:id])
    @driver = @trip.driver

    @trip_registrations = @trip.trip_registrations

     # @whos_going = @trip.regs[:accepted].collect {|r| r.passenger } + @trip.driver

  end


  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:info] = "You have just deleted a trip."
    redirect_to trips_path
  end

  def trip_params
    params.require(:trip).permit(:title, :description, :latitude, :longitude, :departure)
  end

end

Rox/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to user_path(@user)
      return
    end

    render :edit
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def user_trip_search
    @trips = current_user.trips
  end

  def user_params
    params.require(:user).permit(:bio, :email, :climbing_grade, :climbing_style, :favourite_spots)
  end

end

Rox/app/helpers/api/trips_helper.rb
module Api::TripsHelper
end

Rox/app/helpers/application_helper.rb
module ApplicationHelper
end

Rox/app/helpers/home_helper.rb
module HomeHelper
end

Rox/app/helpers/landing_helper.rb
module LandingHelper
end

Rox/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

Rox/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rox/app/helpers/trip_registrations_helper.rb
module TripRegistrationsHelper
end

Rox/app/helpers/trips_helper.rb
module TripsHelper
end

Rox/app/helpers/users_helper.rb
module UsersHelper
end

Rox/app/views/home/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">Your trips coming up</div>
      <div class="panel-body">
        <% if current_user.upcoming.empty? && current_user.soon.empty? %>
          <h4>What's going on? No trips yet!</h4>
          <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips/new" role="button">Plan your own trip</a>
          <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips" role="button">Find me a trip!</a>
        <% else %>
        <ul style="list-style-type: none;">
          <% current_user.upcoming.each do |trips| %>
          <li><%= link_to trips.title, trip_path(trips.id) %></li>
          
          <br/>
          <li><%= trips.departure.strftime("%a %b #{trips.departure.day.ordinalize}") %></li>
          <br/>
          <% end %>
          <% current_user.soon.each do |lifts| %>
          <li><%= link_to lifts.title, trip_path(lifts.id) %></li>
          <br/>
          <li><%= lifts.departure.strftime("%a %b #{lifts.departure.day.ordinalize}") %></li>
          <br/>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
    
    
  </div>
  <div class="col-md-8">
  <div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title" style="text-align:centre;">Best photos of the month sent in by you</h3>
  </div>
  <div class="panel-body">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="/assets/Honnold-topout.jpg" alt="...">
          <div class="carousel-caption">
            
          </div>
        </div>
        <div class="item">
          <img src="/assets/profile.jpg" alt="...">
          <div class="carousel-caption">
            
          </div>
        </div>
        <div class="item">
          <img src="/assets/indiancreek.jpg" alt="...">
          <div class="carousel-caption">
            
          </div>
        </div>
        
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
    
  </div>
</div>
  

Rox/app/views/landing/_login.html.erb
<div class="modal fade" id="loginModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Log in</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="field">
            <%= f.label :email, class: "white" %><br />
            <%= f.email_field :email, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="field">
            <%= f.label :password, class: "white" %><br />
            <%= f.password_field :password, autocomplete: "off", class: "inputs form-control" %>
          </div>
          <% if devise_mapping.rememberable? -%>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me, class: "white" %>
            </div>
          <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Log in", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

Rox/app/views/landing/_signup.html.erb
<div class="modal fade" id="signupModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
          <div class="form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, class: "inputs form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %>
          </div>
          <br />
          <div class="actions">
            <%= f.submit "Save!", class: "btn btn-primary btn-color" %>
          </div>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

Rox/app/views/landing/index.html.erb
<div class="jumbotron" id="jumbotron" style="margin-top: 20px;">
  <h1 id="backdrop" style="border-top: solid black 1px; margin-bottom: 0px; padding-top: 30px;">Hot Rox</h1>
  <h2 id="backdrop" style="border-bottom: solid black 1px; margin-top: 0px; padding-bottom: 30px;">The perfect place to find a trip to the best climbing spots in Spain!</h2>
  
  <ul class="cb-slideshow">
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
    <li>
      <span></span>
      
    </li>
  </ul>
  <div class="container landing">
    <a class="btn btn-primary btn-lg hvr-bounce-in" style="margin-right: 10px;" href="#" data-toggle="modal" data-target="#loginModal" role="button">Log in</a>
    <a class="btn btn-primary btn-lg hvr-bounce-in" style="margin-left: 10px;" href="#" data-toggle="modal" data-target="#signupModal" role="button">Sign up</a>
  </div>
</div>

<%= render "landing/login" %>

<%= render "landing/signup" %>

Rox/app/views/layouts/_flash_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
      <%= content_tag :div, message, class: "alert alert-#{key}" %>
      <% end %>
    </div>
  </div>
</div>

Rox/app/views/layouts/_footer.html.erb
<footer>
  <div class="footer navbar-fixed-bottom voll white">
    <div class="row">
      <div class="col-md-1 col-md-offset-11">
        <%= link_to 'Homepage', root_path %>
      </div>
    </div>
  </div>
</footer>

Rox/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default mycolor">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand hvr-fade" href="/">Hot Rox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="hvr-fade"><%= link_to 'Trips', trips_path %></li>
        <li class="hvr-fade"><%= link_to 'Plan a trip', new_trip_path %></li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        
          <li>
             
              <a href="/users/<%= current_user.id %>" style="padding: 0px;"><img class="media-object" src="<%= gravatar_image_url(current_user.email, size: 50) %>" width="50" height="50" style="border-radius: 100%;"></a>
            
          </li>
          <li class="hvr-fade"><%= link_to 'My trips', my_trips_path(@user) %></li>
          <li class="hvr-fade"><%= link_to 'Log out', destroy_user_session_path, method: 'DELETE' %></li>
          <% else %>
          <li class="hvr-fade"><%= link_to 'Log in', new_user_session_path %></li>
        </ul>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

Rox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hot Rox</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Vollkorn">
    <link rel="icon" type="image/jpg" href="http://www.summitbsa.org/wp-content/uploads/2013/01/GBGW-activities_facebook_profile-pic_climbing.jpg">
    <meta content="width=device-width, initial-scale=1" name="viewport">
  </head>
  <body>
  <% if current_user.present? %>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash_messages" %>
    
    <%= render "layouts/background_items" %>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=#{GOOGLEMAPS}"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

Rox/app/views/trips/_trip_passenger_item.html.erb
  <div class="col-xs-2 col-md-2">
    <a href="<%= user_path(registration.passenger) %>" class="thumbnail">
      <img src="<%= gravatar_image_url(registration.passenger.email, size:50) %>" width="50" height="50"/>
    </a>
  </div>

Rox/app/views/trips/_trip_user_item.html.erb
<li style="list-style-type: none">
<a href="/users/<%= registration.passenger.id%>">
          <img class="media-object" src="<%= gravatar_image_url(registration.passenger.email, size:50) %>" width="50" height="50">
        </a>
  
  Status: <span><%= registration.status %></span>
  <a href="javascript:void(0)" class="btn btn-default btn-xs btn-decline pull-right btn-click" data-confirm="Are you sure?" data-registration-id="<%= registration.id %>">
    <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
  </a>
  <a href="javascript:void(0)" class="btn btn-default btn-xs btn-accept pull-right btn-click" data-confirm="Are you sure?"data-registration-id="<%= registration.id %>">
    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
  </a>
  
</li>
<br/>

Rox/app/views/trips/index.html.erb
<div class="page-header" style="margin-top: 0px;">
  <h1>Find a trip </h1>
</div>
  <div class="row">
    <div class="col-md-4">
<div>
<div class="panel panel-primary">
      <div class="panel-heading">Coming up</div>
      <div class="panel-body">
        
        <ul style="list-style-type: none;">
          <% @next_trips.each do |trip| %>

            <div class="media">
              <div class="media-left">
                <a href="#">
                 <img class="media-object" src="<%= gravatar_image_url(trip.driver.email, size:50) %>" width="50" height="50">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= link_to trip.title, trip_path(trip.id), class: "black" %></h4>
                <%= trip.departure.strftime("%a %b #{trip.departure.day.ordinalize}") %>
              </div>
            </div>
            <% end %>
        </ul>
      </div>
    </div>
  

</div>
    </div>
    <div class="col-md-8">
    <div class="panel panel-primary">
  <div class="panel-heading">Click on any marker to see more info about a trip.</div>
  <div class="panel-body">
      <div id="trip-list-map"></div>
    </div>
    
  </div>
</div>
  </div>


<script>$(document).ready(loadMap());</script>
<script>$('#myTabs a[href="#this_weekend"]').tab('show')</script>

Rox/app/views/trips/new.html.erb
    <div class="col-md-6 col-xs-6">
      
        <h2>Plan your trip</h2>
        <%= form_for [@user, @trip] do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: " form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: " form-control" %>
        </div>
        <br/>

        <div class="form-group">
          <label>Search for your trip starting point below or just click on the map</label>
          <input id="address" type="text" class="inputs form-control" placeholder="Where is your trip starting?" style="width:220px;">
          <br/>
  
          <button class="btn btn-primary btn-sm" id="submit" type="submit">Search</button>
        </div>
        <input type="hidden" name="trip[latitude]" id="latitude">
        <input type="hidden" name="trip[longitude]" id="longitude">
        <br/>

        <!-- <div class="field">
          <h4>Click on the map to choose the trip destination</h4>
        </div>
        <input type="hidden" name="trip[destination_lat]" id="lat">
        <input type="hidden" name="trip[destination_lon]" id="lon">
        <br/> -->
        

        <div class="form-group">
          <%= f.label :departure_date %><br />
          <%= f.date_field :departure, class: " form-control" %>
        </div>
        <br/>
        
        <div class="actions">
          <%= f.submit "Save my trip!", class: "btn btn-primary" %>
        </div>
        <% end %>
      
    </div> 
    <div class="jumbotron">
  <div class="container">
    <div id="new-trip-map" class="col-md-6 col-xs-6"></div>
    
  </div>
</div>  

<script>
  $(function () {
    google.maps.event.addDomListener(window, 'load', createTripInitializeMap);
  })
</script>
      

Rox/app/views/trips/show.html.erb
<div class="col-md-6 col-xs-6">
  <div class="panel panel-primary">
  <div class="panel-heading"><%= @trip.title %></div>
  <div class="panel-body">
    <p><%= @trip.description %></p>
    <p><%= @trip.departure.strftime("%a %b #{@trip.departure.day.ordinalize}") %></p>
    <% if @trip.passengers.blank? %>
    <p>No passengers on this trip yet!</p>
    <% end %>
    
    <% if current_user.id == @trip.driver.id %>
    <ul>
      <% @trip_registrations.each do |registration| %>
      <%= render "trips/trip_user_item", registration: registration %>
      <% end %>
    </ul>

    <%= link_to 'Delete trip', trip_path(@trip), method: 'Delete', class: "btn btn-primary btn-sm btn-color", data: { confirm: "Are you sure?" } %>

    <% else %>
    
      <% @trip.regs[:accepted].each do |registration| %>
      <%= render "trips/trip_passenger_item", registration: registration %>
      <% end %>

      <% if !current_user.on_trip?(@trip) %>
      <%= link_to 'Join trip', trip_trip_registrations_path(@trip), method: 'Post', class: "btn btn-primary btn-sm", style: "margin-left: 10px;", data: { confirm: "Are you sure?" } %>

      <% elsif %>
      <% current_user.trip_status(@trip) == ("pending") %>
      <h5>Your current request for this trip is pending. </h5>
      <% end %>
    
    <% end %>
  </div>
</div>

    
  
</div>
<div class="col-md-6 col-xs-6">
<div class="panel panel-default">
  <div class="panel-body">
  <div id="trip-map-container"></div>
</div>
  </div>
</div>
<script>$(document).ready(loadMap('trip-map-container'));</script>

Rox/app/views/users/_edit_user.html.erb
<div class="modal fade" id="editModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <h2>Edit <%= resource_name.to_s.humanize %></h2>
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= devise_error_messages! %>
        <div class="form-group">
          <%= f.email_field :email, autofocus: true, placeholder: "Email", class:"form-control" %>
        </div>
        <div class="form-group" rows="3">
          <%= f.text_area :bio, autofocus: true, placeholder: "Write about yourself here...", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_field :climbing_grade, autofocus: true, placeholder: "climbing grade", class:"form-control" %>
        </div>
        <div class="form-group" rows="2">
          <%= f.text_area :favourite_spots, autofocus: true, placeholder: "Your favourite climbing spots", class:"form-control" %>
        </div>
        <div class="form-group" rows="1">
          <%= f.text_area :climbing_style, autofocus: true, placeholder: "What's your climbing style?", class:"form-control" %>
        </div>

       
        
        
          <div class="actions">
            <%= f.submit "Update", class: "btn btn-primary btn-color" %>
          </div>
          <% end %>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
    
      
    

Rox/app/views/users/show.html.erb
<div class="jumbotron" id="profile">
  
        <img class="media-object" src="<%= gravatar_image_url(@user.email, size:80) %>" width="80" height="80">
        <br/>
        <h3><%= @user.name %></h3>
        <br/>
        <h5>About me: <p><%= @user.bio %></p></h5>
        <br/>
        <h5>Climbing grade: <p><%= @user.climbing_grade %></p></h5>
        <br/>
        <h5>Favourite spots: <p><%= @user.favourite_spots %></p></h5>
        <br/>
        <h5>Climbing style: <p><%= @user.climbing_style %></p></h5>
        <br/>
        <h5>Email: <p><%= @user.email %></p></h5>
        <br/>
        
        
        <a class="btn btn-primary btn-md hvr-bounce-in" href="#" data-toggle="modal" data-target="#editModal" role="button">Edit my profile</a>
        
</div>

<%= render "/users/edit_user" %>

     

Rox/app/views/users/user_trip_search.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Trips I've planned</div>
      <div class="panel-body">
      <% if current_user.trips.empty? && current_user.lifts.empty? %>
      <h4>You haven't planned any trips yet!</h4>
          <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips/new" role="button">Plan your own trip</a>
          <% else %>
        <% current_user.trips.each do |trip| %>
        <ul>
          <li style="list-style-type: none;"><%= link_to trip.title, trip_path(trip), class: "black-my-trips" %></li>
          <br/>
          <li style="list-style-type: none;">Passengers on this trip: <span class="badge my-trips"><%= trip.passengers.count %></span></li>
        </ul>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>

<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">Trips I've joined</div>
    <div class="panel-body">
    <% if current_user.lifts.empty? %>
    <h4>You haven't joined a trip</h4>
    <a class="btn btn-primary btn-sm hvr-bounce-in" href="/trips" role="button">Find me a trip!</a>
    <% else %>
      <% current_user.lifts.each do |lift| %>
      <ul>
        <li style="list-style-type: none;"><%= link_to lift.title, trip_path(lift) %></li>
        <a href="/users/<%= lift.driver.id%>">
          <img class="media-object" src="<%= gravatar_image_url(lift.driver.email, size:50) %>" width="50" height="50">
        </a>The trip organiser
      </ul>
      <% end %>
      <% end %>
    </div>
  </div>
  </div>
</div>